export const skillsData = [
  { name: "HTML" },
  { name: "CSS" },
  { name: "JavaScript" },
  { name: "React.js" },
  { name: "Redux" },
  { name: "Next.js" },
  { name: "Vue.js" },
  { name: "Tailwind CSS" },
  { name: "Material UI" },
  { name: "Node.js" },
  { name: "Express.js" },
  { name: "Laravel" },
  { name: "MySQL" },
  { name: "MongoDB" },
  { name: "Mongoose" },
  { name: "Git" },
  { name: "GitHub" },
  { name: "Redis" },
  { name: "Docker" },
  { name: "Socket.io" },
  { name: "JWT" },
  { name: "Node-Mailer" },
  { name: "Firebase" },
  { name: "Cloudinary" },
  { name: "REST API" },
  { name: "Postman" },
  { name: "Vercel" },
  { name: "Render" },
];
